//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Id { get; set; }
        public string bzname { get; set; }
        public byte[] photo { get; set; }
        public string description { get; set; }
        public int purpose { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public int paid { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string instagram { get; set; }
        public string youtube { get; set; }
        public System.DateTime reg_date { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
